import React from 'react';
import { Veridical, VeridicalEditorPlugins } from 'veridical';
import {
    TreeViewPlugin,
    EditorFromStatePlugin,
    EditorStatePlugin,
} from '@veridical/plugins';
import { defaultVeridicalTheme } from '@veridical/utils';

const previousEditorState = {
    root: {
        children: [
            {
                children: [
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Heading 1 is here and it can be long',
                        type: 'text',
                        version: 1,
                    },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'heading',
                version: 1,
                tag: 'h1',
            },
            {
                src: 'https://images.unsplash.com/photo-1661961110372-8a7682543120?ixlib=rb-4.0.3&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                altText: 'Laptop Image',
                height: 780,
                width: 1170,
                type: 'image',
                version: 1,
            },
            {
                children: [
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Heading 2 is here',
                        type: 'text',
                        version: 1,
                    },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'heading',
                version: 1,
                tag: 'h2',
            },
            {
                children: [
                    {
                        children: [
                            {
                                detail: 0,
                                format: 0,
                                mode: 'normal',
                                style: '',
                                text: 'Heading 3 is here',
                                type: 'text',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 1,
                        rel: 'noopener',
                        target: null,
                        url: 'https://raghavpandit.in',
                    },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'heading',
                version: 1,
                tag: 'h3',
            },
            {
                children: [
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'import',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'keyword',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '{',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' useEffect ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '}',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'from',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'keyword',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '"react"',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'string',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ';',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'const',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'keyword',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' name ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '=',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'operator',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '"Raghav"',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'string',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ';',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'function',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'keyword',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'printName',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'function',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '(',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'name',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'parameter',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ')',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '{',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '  console',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '.',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'log',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'function',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '(',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'name',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ')',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ';',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '}',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'printName',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'function',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '(',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'name',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ')',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ';',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'class',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'keyword',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'ImageNode',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'class-name',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'extends',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'keyword',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'DecoratorNode',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'class-name',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '<',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'operator',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'JSX',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'constant',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '.',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Element',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '>',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'operator',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '{',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '  ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '__src',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'literal-property',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ':',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'operator',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' string',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ';',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '  ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '__width',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'literal-property',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ':',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'operator',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' number',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ';',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '  ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '__height',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'literal-property',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ':',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'operator',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' number',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ';',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '  ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'constructor',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'function',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '(',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ')',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '{',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '    ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'this',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'keyword',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '.',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '__width ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '=',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'operator',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'this',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'keyword',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '.',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '__height ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '=',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'operator',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '10',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'number',
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ';',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '  ',
                        type: 'code-highlight',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '}',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '}',
                        type: 'code-highlight',
                        version: 1,
                        highlightType: 'punctuation',
                    },
                    {
                        type: 'linebreak',
                        version: 1,
                    },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'code',
                version: 1,
                language: 'javascript',
            },
            {
                children: [
                    {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Here is some normal paragraph text',
                        type: 'text',
                        version: 1,
                    },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
            },
            {
                children: [
                    {
                        children: [
                            {
                                detail: 0,
                                format: 0,
                                mode: 'normal',
                                style: '',
                                text: 'This  is a Unordered list',
                                type: 'text',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'listitem',
                        version: 1,
                        value: 1,
                    },
                    {
                        children: [
                            {
                                detail: 0,
                                format: 0,
                                mode: 'normal',
                                style: '',
                                text: 'This is another item',
                                type: 'text',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'listitem',
                        version: 1,
                        value: 2,
                    },
                    {
                        children: [
                            {
                                children: [
                                    {
                                        children: [
                                            {
                                                detail: 0,
                                                format: 0,
                                                mode: 'normal',
                                                style: '',
                                                text: 'this is sub item',
                                                type: 'text',
                                                version: 1,
                                            },
                                        ],
                                        direction: 'ltr',
                                        format: '',
                                        indent: 1,
                                        type: 'listitem',
                                        version: 1,
                                        value: 1,
                                    },
                                    {
                                        children: [
                                            {
                                                children: [
                                                    {
                                                        children: [
                                                            {
                                                                detail: 0,
                                                                format: 0,
                                                                mode: 'normal',
                                                                style: '',
                                                                text: 'this sub sub item',
                                                                type: 'text',
                                                                version: 1,
                                                            },
                                                        ],
                                                        direction: 'ltr',
                                                        format: '',
                                                        indent: 2,
                                                        type: 'listitem',
                                                        version: 1,
                                                        value: 1,
                                                    },
                                                    {
                                                        children: [
                                                            {
                                                                children: [
                                                                    {
                                                                        children:
                                                                            [
                                                                                {
                                                                                    detail: 0,
                                                                                    format: 0,
                                                                                    mode: 'normal',
                                                                                    style: '',
                                                                                    text: 'this is sub sub sub item',
                                                                                    type: 'text',
                                                                                    version: 1,
                                                                                },
                                                                            ],
                                                                        direction:
                                                                            'ltr',
                                                                        format: '',
                                                                        indent: 3,
                                                                        type: 'listitem',
                                                                        version: 1,
                                                                        value: 1,
                                                                    },
                                                                ],
                                                                direction:
                                                                    'ltr',
                                                                format: '',
                                                                indent: 0,
                                                                type: 'list',
                                                                version: 1,
                                                                listType:
                                                                    'bullet',
                                                                start: 1,
                                                                tag: 'ul',
                                                            },
                                                        ],
                                                        direction: null,
                                                        format: '',
                                                        indent: 2,
                                                        type: 'listitem',
                                                        version: 1,
                                                        value: 2,
                                                    },
                                                ],
                                                direction: 'ltr',
                                                format: '',
                                                indent: 0,
                                                type: 'list',
                                                version: 1,
                                                listType: 'bullet',
                                                start: 1,
                                                tag: 'ul',
                                            },
                                        ],
                                        direction: 'ltr',
                                        format: '',
                                        indent: 1,
                                        type: 'listitem',
                                        version: 1,
                                        value: 2,
                                    },
                                ],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                type: 'list',
                                version: 1,
                                listType: 'bullet',
                                start: 1,
                                tag: 'ul',
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'listitem',
                        version: 1,
                        value: 3,
                    },
                    {
                        children: [
                            {
                                detail: 0,
                                format: 0,
                                mode: 'normal',
                                style: '',
                                text: 'Final item',
                                type: 'text',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'listitem',
                        version: 1,
                        value: 3,
                    },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'list',
                version: 1,
                listType: 'bullet',
                start: 1,
                tag: 'ul',
            },
            {
                children: [],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
            },
            {
                children: [
                    {
                        children: [
                            {
                                detail: 0,
                                format: 0,
                                mode: 'normal',
                                style: '',
                                text: 'This is ordered list',
                                type: 'text',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'listitem',
                        version: 1,
                        value: 1,
                    },
                    {
                        children: [
                            {
                                detail: 0,
                                format: 0,
                                mode: 'normal',
                                style: '',
                                text: 'another item',
                                type: 'text',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'listitem',
                        version: 1,
                        value: 2,
                    },
                    {
                        children: [
                            {
                                children: [
                                    {
                                        children: [
                                            {
                                                detail: 0,
                                                format: 0,
                                                mode: 'normal',
                                                style: '',
                                                text: 'this sub item',
                                                type: 'text',
                                                version: 1,
                                            },
                                        ],
                                        direction: 'ltr',
                                        format: '',
                                        indent: 1,
                                        type: 'listitem',
                                        version: 1,
                                        value: 1,
                                    },
                                    {
                                        children: [
                                            {
                                                children: [
                                                    {
                                                        children: [
                                                            {
                                                                detail: 0,
                                                                format: 0,
                                                                mode: 'normal',
                                                                style: '',
                                                                text: 'sub sub item',
                                                                type: 'text',
                                                                version: 1,
                                                            },
                                                        ],
                                                        direction: 'ltr',
                                                        format: '',
                                                        indent: 2,
                                                        type: 'listitem',
                                                        version: 1,
                                                        value: 1,
                                                    },
                                                    {
                                                        children: [
                                                            {
                                                                children: [
                                                                    {
                                                                        children:
                                                                            [
                                                                                {
                                                                                    detail: 0,
                                                                                    format: 0,
                                                                                    mode: 'normal',
                                                                                    style: '',
                                                                                    text: 'sub sub sub item',
                                                                                    type: 'text',
                                                                                    version: 1,
                                                                                },
                                                                            ],
                                                                        direction:
                                                                            'ltr',
                                                                        format: '',
                                                                        indent: 3,
                                                                        type: 'listitem',
                                                                        version: 1,
                                                                        value: 1,
                                                                    },
                                                                ],
                                                                direction:
                                                                    'ltr',
                                                                format: '',
                                                                indent: 0,
                                                                type: 'list',
                                                                version: 1,
                                                                listType:
                                                                    'number',
                                                                start: 1,
                                                                tag: 'ol',
                                                            },
                                                        ],
                                                        direction: null,
                                                        format: '',
                                                        indent: 2,
                                                        type: 'listitem',
                                                        version: 1,
                                                        value: 2,
                                                    },
                                                ],
                                                direction: 'ltr',
                                                format: '',
                                                indent: 0,
                                                type: 'list',
                                                version: 1,
                                                listType: 'number',
                                                start: 1,
                                                tag: 'ol',
                                            },
                                        ],
                                        direction: 'ltr',
                                        format: '',
                                        indent: 1,
                                        type: 'listitem',
                                        version: 1,
                                        value: 2,
                                    },
                                ],
                                direction: 'ltr',
                                format: '',
                                indent: 0,
                                type: 'list',
                                version: 1,
                                listType: 'number',
                                start: 1,
                                tag: 'ol',
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'listitem',
                        version: 1,
                        value: 3,
                    },
                    {
                        children: [
                            {
                                detail: 0,
                                format: 0,
                                mode: 'normal',
                                style: '',
                                text: 'final item',
                                type: 'text',
                                version: 1,
                            },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'listitem',
                        version: 1,
                        value: 3,
                    },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'list',
                version: 1,
                listType: 'number',
                start: 1,
                tag: 'ol',
            },
            {
                children: [],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
            },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
    },
};

export default function Editor() {
    return (
        <Veridical initialConfig={{ theme: defaultVeridicalTheme }}>
            <VeridicalEditorPlugins />
            {/*<TreeViewPlugin />*/}
            {
                <EditorStatePlugin
                    onChange={({ editorState }) => {
                        console.log(JSON.stringify(editorState));
                    }}
                />
            }
            {
                <EditorFromStatePlugin
                    stringifiedEditorState={JSON.stringify(previousEditorState)}
                />
            }
        </Veridical>
    );
}
